FROM php:8.1-fpm

ARG group
ARG user

# Set working directory
WORKDIR /var/www

# Install system dependencies
RUN apt-get update -y && apt-get install -y \
      bash \
      git \
      unzip \
      git \
      supervisor \
      libzip-dev \
      libpng-dev  \
      libmagickwand-dev --no-install-recommends \
      vim \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-configure intl \
    && docker-php-ext-install \
      pdo_mysql \
      zip \
      gd \
    && rm -rf /tmp/* \
    && rm -rf /var/list/apt/* \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Install PHP extensions
RUN true

RUN docker-php-ext-install exif pcntl bcmath

RUN true

RUN git clone https://github.com/Imagick/imagick \
    && cd imagick \
    && phpize && ./configure \
    && make \
    && make install

RUN true

RUN docker-php-ext-enable imagick

RUN true

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Create user for laravel application
RUN usermod -G www-data -g www-data -s /bin/sh -u 1000  www-data && adduser www-data sudo

# Set permissions
RUN chown $user:$user /var/www

USER $user

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
