FROM php:7.4-fpm-alpine

# Arguments defined in docker-compose.yml
#ENV group="www-data"
#ENV user="www-data"
#ENV uid=1000

# Set working directory
WORKDIR /var/www

# Create user for laravel application
RUN groupadd -g $1000 www-data && useradd -G www-data -g www-data -s /bin/sh -u 1000  www-data

# Set permissions
RUN chown www-data:www-data /var/www

# Install PHP extensions
#RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd
RUN docker-php-ext-install pdo pdo_mysql

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

USER www-data

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
